### PR TITLE
Cleaned Root

### PR DESCRIPTION
**Pull request by diligamer**
Also, no code that references The Files has been changed, because I use VS Code.

### CODE REVIEW

**Comment by yaichenbaum** [comment]
Your changes are good, I just need two things to be fixed before I can merge them.
- The readme has the wrong path to the logo file now.
- Refactor was spelled wrong.

**Comment by diligamer** [comment]
> Your changes are good, I just need two things to be fixed before I can merge them.
> 
> * The readme has the wrong path to the logo file now.
> * Refactor was spelled wrong.

What Logo File

**Comment by yaichenbaum** [comment]
image

**Comment by diligamer** [comment]
The Logo File Still Exists
The Icon

**Comment by yaichenbaum** [comment]
Test on your fork, with your changes, the readme won't display the logo.

**Comment by diligamer** [comment]
My Fork Doesn't Exist.

**Comment by yaichenbaum** [comment]
@diligamer I think you do, otherwise, you wouldn't have been able to open this pull request 🤔

**Comment by diligamer** [comment]
Replace The `  Quick Pad Logo` with `  Quick Pad Logo`

**Comment by diligamer** [comment]
> @diligamer I think you do, otherwise, you wouldn't have been able to open this pull request 🤔

I Deleted It!

**Comment by yaichenbaum** [comment]
That explains it 😆
I will try to make the change manually, thanks for your help 🙂

**Comment by yaichenbaum** [comment]
@diligamer The changes are now in `develop`. Thank you for your help!

**Pull request merged**
