### PR TITLE
Translatations fix

### PR DESCRIPTION
**Pull request by ray1997**
- Property added Italian
- Import and recycle "GiveChanceToSave"

Some more Italian text still missing, @YohskDista please complete the translation properly this time
Also, check the translation.md too https://github.com/UWPCommunity/Quick-Pad/blob/dev/translator.md

### CODE REVIEW

**Comment by YohskDista** [comment]
Sorry for this, I will check it this afternoon.

**Comment by YohskDista** [comment]
Would you give me the write permission to this PR so that I can make the changes or you prefere that I do this on another branch ?

**Comment by yaichenbaum** [comment]
@YohskDista I would prefer you do it on another branch. Thanks for your help!
@ray1997 looks like a merge conflict, as soon as that is solved I will merge it, thanks.

**Comment by yaichenbaum** [comment]
@ray1997 I was able to resolve the merge conflict, thanks for your help.

**Pull request merged**
