### PR TITLE
full italian translation

### PR DESCRIPTION
**Pull request by msavazzi**

### CODE REVIEW

**Comment by yaichenbaum** [comment]
@msavazzi thank you for your pull request, it looks like instead of modifying the xlf file you modified the resw file instead. Once that is fixed I will be able to merge the pull request.

**Comment by msavazzi** [comment]
> @msavazzi thank you for your pull request, it looks like instead of modifying the xlf file you modified the resw file instead. Once that is fixed I will be able to merge the pull request.

I have to check as I followed the instructions in the translator.md file. So I worked with the multilingual editor.
Trying to redo again

**Comment by msavazzi** [comment]
> > @msavazzi thank you for your pull request, it looks like instead of modifying the xlf file you modified the resw file instead. Once that is fixed I will be able to merge the pull request.
> 
> I have to check as I followed the instructions in the translator.md file. So I worked with the multilingual editor.
> Trying to redo again

Ok I did it again, fixed the text and worked only on the xlf file... but VS modifies the project (to add italian file) and I think the resw file is created automatically

**Comment by yaichenbaum** [comment]
>Ok I did it again, fixed the text and worked only on the xlf file... but VS modifies the project (to add italian file) and I think the resw file is created automatically
Yes, the resw file is created automatically when building the app.

**Pull request merged**
