### PR TITLE
New top + french localization

### PR DESCRIPTION
**Pull request by FJduFou**
top: contributors button + release button + center logo

### CODE REVIEW

**Comment by yaichenbaum** [comment]
I had to revert the changes since it wasn't working to add them, can you try reopening you prs under one pr and target the dev branch?
Thanks
Yair

**Comment by FJduFou** [comment]
i don't have understand

**Comment by ray1997** [comment]
@FJduFou Please upload it again to "dev" instead of "master"

**Comment by FJduFou** [comment]
okki, thx

**Comment by yaichenbaum** [comment]
Are you on Discord or anywhere I can get in touch with you when there is an update needed to the translations?

**Comment by FJduFou** [comment]
yes, of course, put your tag and I'll add you tomorrow night

**Comment by yaichenbaum** [comment]
Yair#3380

**Comment by FJduFou** [comment]
i can'y add you
my tag is: ╲⎝⧹⎫⎝ FJ®⎠⎧⧸⎠╱#3224

**Comment by yaichenbaum** [comment]
Join https://discord.gg/zzyzRU and then you can get through to me there

**Pull request merged**
