### PR TITLE
Background color for the splash screen

### PR DESCRIPTION
**Pull request by FJduFou**
https://www.color-hex.com/color/2f2f2f
Transition from blue to dark
-> Possible improvement using the Windows default theme

### CODE REVIEW

**Comment by yaichenbaum** [comment]
Can you test and let me know how long the splash screen shows for you?

**Comment by FJduFou** [comment]
a tiny moment

**Comment by FJduFou** [comment]
noo, it's horrible 😣

**Comment by yaichenbaum** [comment]
How would it look with you change?

**Comment by FJduFou** [comment]
image

**Comment by yaichenbaum** [comment]
Can you do one with the full app windows again?

**Comment by FJduFou** [comment]
no because I can not generate the project, my pc does not seem to support but I will try again ...

**Comment by FJduFou** [comment]
better color: #222224
https://www.color-hex.com/color/222224

**Pull request closed without merging**
